### ISSUE TITLE
Offset tracking

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/osiris#5]
Osiris should provide a means for readers to persist and retrieve their last completed offset so that they can resume after a disconnection, restart etc without needing to persist the offset somewhere external (e.g. a database).

The tracking state takes the shape of a logic map of `TrackingId => offset()` where the tracking Id is an opaque binary with a maximum size of 256 bytes (in order to keep the state use to a reasonable level).

It makes a certain sense to use the log to store the tracking state. This will means introducing two new element to the segment format:

1. At the beginning of each segment the entire current tracking state is persisted. This is effectively a snapshot at this point in time.
2. As offset persistence requests come in they are added to the log as a special new entry, inserted in between chunks. This entry contains tracking state delta updates, e.i. only those new tracking id offset tuples received in the current writer batch.

Given the above to recover after a restart the osiris writer process needs to read the initial snapshot state of the last segment in the log then scan the entirety of this segment and apply the delta updates. Should this prove prohibitively slow snapshots could be taken more frequently than every new segment. I doubt this will be necessary however.

Pruning:

The tracking map is theoretically unbounded meaning we need a strategy to prune entries to stop it growing too large over time. I suggest we try the following approach:

After each retention run we simply drop all tracking ids that have  an offset that is lower than the first offset in the log. This way they won't be included in the next tracking state snapshot and thus will never appear again unless they write again.

The actual tracking map could be kept in an ETS table for easy external querying.

**Comment by acogoluegnes** [comment]
Do this imply that every reader request to persist an offset will have to go through the writer, that is the leader of the log?

**Comment by kjnilsson** [comment]
Yes

**Comment by kjnilsson** [comment]
This is done.
