### ISSUE TITLE
Reading TLS dist options can result in a parse error

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/osiris#78]
To reproduce the error, create an `inter_node_tls.config` file that uses the `{match_fun, ...}` setting, as this file does:

https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/docs/examples/mtls-inter-node/inter_node_tls.config

When osiris starts and reads the file using `file:consult`, the following error will happen:

```
2022-05-25 11:30:04.910132+00:00 [warning] <0.130.0> Error while reading TLS distributon option file /etc/rabbitmq/inter-node-tls.config: {1,
2022-05-25 11:30:04.910132+00:00 [warning] <0.130.0> erl_parse,
2022-05-25 11:30:04.910132+00:00 [warning] <0.130.0> "bad term"}
```

This is due to the fact that `file:consult` doesn't handle in-line function calls. [`file:script`](https://www.erlang.org/doc/man/file.html#script-1) may be able to be used. Here's where Erlang reads the `ssl_dist_optfile`:

https://github.com/erlang/otp/blob/master/lib/ssl/src/ssl_dist_sup.erl

References:
* https://groups.google.com/g/rabbitmq-users/c/9It3mKEbc84
* #57
* #16

**Comment by lukebakken** [comment]
Also note that the log message is formatted over several lines.

**Comment by lukebakken** [comment]
As a workaround, a user can do the following:
* Create the file `custom_match_fun.erl` with the following contents:
    ```
    -module(custom_match_fun).

    -export([match/2]).

    match(ReferenceId, PresentedId) ->
        F = public_key:pkix_verify_hostname_match_fun(https),
        F(ReferenceId, PresentedId).
    ```
* Compile the module:
    ```
    erlc custom_match_fun.erl
    ```
* Run the following to get the code search path directories:
    ```
    rabbitmqctl eval 'code:get_path().'
    ```
* Copy the `custom_match_fun.beam` file to one of the directories returned from the above command, for instance:
    ```
    /opt/rabbitmq/plugins/rabbit-3.10.2/ebin
    ```
* Use the following configuration:
    ```
    [
        {server, [
            {cacertfile, "/etc/rabbitmq/certs/ca.crt"},
            {certfile,   "/etc/rabbitmq/certs/tls.crt"},
            {keyfile,    "/etc/rabbitmq/certs/tls.key"},
            {secure_renegotiate, true},
            {fail_if_no_peer_cert, true},
            {verify, verify_peer},
            {customize_hostname_check, [
            {match_fun, fun custom_match_fun:match/2}
            ]}
        ]},
        {client, [
            {cacertfile, "/etc/rabbitmq/certs/ca.crt"},
            {certfile,   "/etc/rabbitmq/certs/tls.crt"},
            {keyfile,    "/etc/rabbitmq/certs/tls.key"},
            {secure_renegotiate, true},
            {fail_if_no_peer_cert, true},
            {verify, verify_peer},
            {customize_hostname_check, [
            {match_fun, fun custom_match_fun:match/2}
            ]}
        ]}
    ].
    ```

**Comment by lukebakken** [comment]
I threw together some code we could use to read the configuration in the same manner as OTP:

https://github.com/lukebakken/ssl_consult

We would use it in osiris as well as here in rabbitmq-server:

https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl

@michaelklishin @acogoluegnes @dumbbell WDYT?

**Comment by michaelklishin** [comment]
@lukebakken no objections. I'd rename the functions a bit, happy to submit a PR if others agree with the general approach.

**Comment by lukebakken** [comment]
@michaelklishin I invited you to the repo, knock yourself out. No need for a PR. I figure once we get the over-all thumbs-up I'll transfer it to the RabbitMQ org.

**Comment by michaelklishin** [comment]
I cannot push directly:

```
remote: Permission to lukebakken/ssl_consult.git denied to michaelklishin.
fatal: unable to access 'https://github.com/lukebakken/ssl_consult.git/': The requested URL returned error: 403
```

so I will submit a PR instead.

**Comment by michaelklishin** [comment]
Sorry, I had to accept your invitation 🤦‍♂️. Pushed.

**Comment by acogoluegnes** [comment]
Are we going to include the `ssl_consult` module in the RabbitMQ code base? I think a separate library is overkill.

Note we're not supposed to use some RabbitMQ code in Osiris. If we include `ssl_consult` in RabbitMQ code base, we can pass in the `Mod:Fun` to use in Osiris and use `ssl_consult` from RabbitMQ when calling Osiris. The Osiris default would be `file:consult` as it works for most cases.

**Comment by michaelklishin** [comment]
Yeah, we can include that module into RabbitMQ itself. Maybe prefixed with RabbitMQ, too.

**Comment by acogoluegnes** [comment]
Sounds good. Then we'll have to use something like the `Mod:Fun` parameter trick for Osiris to use it.

**Comment by lukebakken** [comment]
OK I'll put `ssl_consult` into the RabbitMQ code.

**Comment by acogoluegnes** [comment]
@lukebakken @michaelklishin Unless I'm missing something, this is not fully fixed as Osiris still [calls `file:consult`](https://github.com/rabbitmq/osiris/blob/43edcd2a60e8cfff3d23767d37b6d6efe105cdfa/src/osiris_util.erl#L124) and RabbitMQ [calls](https://github.com/rabbitmq/rabbitmq-server/blob/744100ed2fcc0b4ce137a9fd9df4ba3ba5839997/deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_conf.erl#L93) this code.

**Comment by acogoluegnes** [comment]
After some testing I confirm that using an inter-node configuration like the following makes Osiris replication over TLS configuration fail:

```erlang
[
  {server, [
    {cacertfile, "/etc/rabbitmq/certs/ca.crt"},
    {certfile,   "/etc/rabbitmq/certs/tls.crt"},
    {keyfile,    "/etc/rabbitmq/certs/tls.key"},
    {secure_renegotiate, true},
    {fail_if_no_peer_cert, true},
    {verify, verify_peer},
    {customize_hostname_check, [
      {match_fun, public_key:pkix_verify_hostname_match_fun(https)}
    ]}
  ]},
  {client, [
    {cacertfile, "/etc/rabbitmq/certs/ca.crt"},
    {certfile,   "/etc/rabbitmq/certs/tls.crt"},
    {keyfile,    "/etc/rabbitmq/certs/tls.key"},
    {secure_renegotiate, true},
    {fail_if_no_peer_cert, true},
    {verify, verify_peer},
    {customize_hostname_check, [
      {match_fun, public_key:pkix_verify_hostname_match_fun(https)}
    ]}
  ]}
].
```

```
2022-06-07 14:28:13.928487+02:00 [debug] <0.139.0> == Configuration ==
2022-06-07 14:28:13.928525+02:00 [debug] <0.139.0> Setting default config
2022-06-07 14:28:13.929464+02:00 [debug] <0.139.0> Inter-node TLS enabled, configuring stream replication over TLS
2022-06-07 14:28:13.929494+02:00 [debug] <0.139.0> Using ssl_dist_optfile to configure stream replication over TLS
2022-06-07 14:28:13.929857+02:00 [warning] <0.139.0> Error while reading TLS distributon option file /tmp/rabbitmq_server_tls_replication/etc/rabbitmq/inter_node_tls.config: {1,
2022-06-07 14:28:13.929857+02:00 [warning] <0.139.0>                                                                                                                           erl_parse,
2022-06-07 14:28:13.929857+02:00 [warning] <0.139.0>                                                                                                                           "bad term"}
2022-06-07 14:28:13.929925+02:00 [warning] <0.139.0> Stream replication over TLS will NOT be enabled
```
